site_name: blocksets

nav:
  - Home: index.md
  - Installation and Usage: install_use.md
  - Terminology: terminology.md
  - Classes: classes.md
  - Thoughts and Ideas: thoughts.md
  - Contribution: contribution.md
  - Reference: code.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            heading_level: 3
            members_order: source

theme:
  name: readthedocs
